# Generated by Django 4.2.11 on 2026-04-19 05:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('url', 'url'), ('repo', 'repo'), ('file', 'file')], max_length=10)),
                ('input_value', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=10)),
                ('current_layer', models.IntegerField(default=1)),
                ('surfaces_covered', models.JSONField(default=list)),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('layer', models.IntegerField()),
                ('surface', models.CharField(max_length=100)),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_args', models.JSONField(default=dict)),
                ('raw_output', models.TextField(blank=True)),
                ('parsed_output', models.JSONField(default=dict)),
                ('findings_count', models.IntegerField(default=0)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('pivot_reason', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='scans.scan')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('attack_narrative', models.TextField()),
                ('findings_count', models.JSONField(default=dict)),
                ('surfaces_tested', models.JSONField(default=list)),
                ('chains_found', models.JSONField(default=list)),
                ('risk_score', models.FloatField(default=0.0)),
                ('raw_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scans.scan')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'critical'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('info', 'info')], max_length=10)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=100)),
                ('cve_id', models.CharField(blank=True, max_length=30)),
                ('cwe_id', models.CharField(blank=True, max_length=20)),
                ('layer', models.IntegerField()),
                ('surface', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('evidence', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('is_chained', models.BooleanField(default=False)),
                ('chained_from', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scans.scan')),
                ('scan_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scans.scanstep')),
            ],
        ),
    ]
