# Generated by Django 4.2.11 on 2026-04-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('paused', 'paused'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=10),
        ),
    ]
